#!/bin/bash


usage() {
	echo "$0: execute command on a netns of a specified docker container"
	echo "Usage: $0 [container id] command arguments"
	exit 1
}

set -eu

if [ $# -lt 1 ]; then
	usage
fi

cid=$1

# remove cid
shift 1

netnsdir="/var/run/netns"

if [ ! -e $netnsdir ]; then
	mkdir -p $netnsdir
fi

# create symlink for container netns on /var/run/netns
docker_nsdir=$(docker inspect $cid --format "{{.NetworkSettings.SandboxKey}}")
docker_nsid=$(docker inspect $cid --format "{{.NetworkSettings.SandboxID}}")
docker_nsid=${docker_nsid:0:12}
nsname=docker-netns-$docker_nsid
nsdir=/var/run/netns/$nsname

if [ -e dockernsdir ]; then
	rm $nsdir
fi
ln -sf $docker_nsdir $nsdir

# execute command on the netns
ip netns exec $nsname $@

# clean up
rm $nsdir
